spring:
    threads:
        virtual:
            enabled: true
    application:
        name: api
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:local}
    jackson:
        time-zone: Asia/Seoul
        default-property-inclusion: non_null

server:
    http2:
        enabled: true
    servlet:
        context-path: /api
    shutdown: graceful
    compression:
        enabled: true
        mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,text/javascript,web/json,web/xml
        min-response-size: 500B
