spring:
    threads:
        virtual:
            enabled: true
    application:
        name: api
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:local}
    web:
        resources:
            cache:
                period: 3600
    jackson:
        time-zone: Asia/Seoul
        default-property-inclusion: non_null
        deserialization:
            fail-on-unknown-properties: false

server:
    servlet:
        context-path: /api
    shutdown: graceful
    forward-headers-strategy: framework
